[languages]
  [languages.fi]
    languageName = "FI"
    contentDir = "content/finnish"
    languageCode = "fi-fi"
    weight = 1
  [languages.en]
    languageName = "EN"
    contentDir = "content/english"
    languageCode = "en-us"
    weight = 2