############# Finnish navigation ##############

[[main]]
name = "Pianist"
url = "/en/piano"
weight = 1

[[main]]
name = "Photographer"
url = "/en/photography"
weight = 2

[[main]]
name = "Contact"
url = "/en/contact"
weight = 3


# footer menu
[[footer]]
name = "Pianist"
url = "/en/piano"
weight = 1

[[footer]]
name = "Photographer"
url = "/en/photography"
weight = 2

[[footer]]
name = "Contact"
url = "/en/contact"
weight = 3
